---
servers:
  vars:
    ansible_user: vagrant
    ansible_become: true
  hosts:
    srv100:
      ansible_ssh_private_key_file: /home/vagrant/keys/srv100/private_key 
#      ansible_ssh_private_key_file: /vagrant/.vagrant/machines/srv100/virtualbox/private_key
      ansible_host: 172.16.128.100

