# site.yml
---
- name: Configure srv100 # Each task should have a name
  hosts: srv100          # Indicates hosts this applies to (host or group name)
  roles:                 # Enumerate roles to be applied
    - bertvv.rh-base
    - bertvv.httpd
  tasks:
    - name: Copy the database creation script (db.sql) to the server
      ansible.builtin.copy:
        src: /vagrant/ansible/files/db.sql
        dest: /tmp/
    - name: Copy the php script (test.php) to the server and renaming it (index.php)
      ansible.builtin.copy:
        src: /vagrant/ansible/files/test.php
        dest: /var/www/html/index.php
    - name: Initializing the database
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: import
        target: /tmp/db.sql
        login_unix_socket: /var/lib/mysql/mysql.sock
    - name: Create database user with all database privileges
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL'
        login_unix_socket: /var/lib/mysql/mysql.sock
